dist: trusty
group: travis_latest

language: go

go:
  - "1.12.x"

# first part of the GOARCH workaround
# setting the GOARCH directly doesn't work, since the value will be overwritten later
# so set it to a temporary environment variable first
env:
  global:
    - TIMESCALE_FACTOR=20
    - GO111MODULE=on
  matrix:
    - TRAVIS_GOARCH=amd64 TESTMODE=lint
    - TRAVIS_GOARCH=amd64 TESTMODE=unit
    - TRAVIS_GOARCH=amd64 TESTMODE=integration
    - TRAVIS_GOARCH=386 TESTMODE=unit
    - TRAVIS_GOARCH=386 TESTMODE=integration


# second part of the GOARCH workaround
# now actually set the GOARCH env variable to the value of the temporary variable set earlier
before_install:
  - travis_retry go get golang.org/x/tools/cmd/cover
  - travis_retry go get github.com/onsi/ginkgo/ginkgo
  - travis_retry go get github.com/onsi/gomega
  - export GOARCH=$TRAVIS_GOARCH
  - go env # for debugging
  - travis_retry go get -t ./...
  - "export DISPLAY=:99.0"
  - "Xvfb $DISPLAY &> /dev/null &"

script:
  - | 
    if [ ${TESTMODE} == "lint" ]; then
      travis_retry curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.15.0
    fi
  - .travis/script.sh


after_success:
  - .travis/after_success.sh
