on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go install ./...
      - name: Check that no non-test files import Ginkgo or Gomega
        run: .github/workflows/no_ginkgo.sh
      - name: Check that go.mod is tidied
        run: |
          cp go.mod go.mod.orig
          cp go.sum go.sum.orig
          go mod tidy
          cmp go.mod go.mod.orig
          cmp go.sum go.sum.orig
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.31
